/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package burbuja;

import java.util.ArrayList;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class Burbuja extends javax.swing.JFrame {

    int i = 0;
    int j = 0;
    int k = 0;
    int x = 0;
    int y = 0;
    int s = 0;
    int aux = 0;
    int inicio = 0;
    int contador = 0;
    String mensaje = "";
    String entrada1 = "";
    String temporal = "";
    String datos = "";
    String espacio[] = {" "};
    ArrayList burbuja = new ArrayList();
    ArrayList memoria = new ArrayList();

    public void LimpiarTxt() {
        jTextField1Entrada.setText("");
        this.setLocationRelativeTo(null);
    }

    /**
     * Creates new form Burbuja
     */
    public Burbuja() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jTextField1Entrada = new javax.swing.JTextField();
        jButtonContenido = new javax.swing.JButton();
        jButtonOrdenar = new javax.swing.JButton();
        jButtonNuevo = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("METODO DE LA BURBUJA ");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setText("Memoria Dinamica");

        jButtonGuardar.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jTextField1Entrada.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonContenido.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jButtonContenido.setText("Contenido");
        jButtonContenido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonContenido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonContenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContenidoActionPerformed(evt);
            }
        });

        jButtonOrdenar.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jButtonOrdenar.setText("Ordenar");
        jButtonOrdenar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonOrdenar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarActionPerformed(evt);
            }
        });

        jButtonNuevo.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });

        jButtonSalir.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField1Entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(jButtonContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jTextField1Entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonOrdenar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevo)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        {//GEN-FIRST:event_jButtonGuardarActionPerformed
            try {
                datos = jTextField1Entrada.getText();//entrada de datos
                datos += " ";//sumo un espacio para guardar el ultimo dato en el arreglo

                //Llenado del arreglo
                for (i = 0; i < datos.length(); i++) {

                    entrada1 = datos.substring(i, i + 1);//extrae caracter por caracter

                    if (!entrada1.equals(espacio[0]))//si es diferente a un espacio se ejecuta
                    {
                        temporal += entrada1;
                    } else if (entrada1.equals(espacio[0])) { //si es igual a un espacio se ejecuta
                        burbuja.add(temporal); //deposita en el arreglo
                        temporal = "";
                        k++;
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Datos invalidos, porfavor vuelve a intentar");
            }
        }//GEN-LAST:event_jButtonGuardarActionPerformed
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContenidoActionPerformed
        {//GEN-FIRST:event_jButtonContenidoActionPerformed
            //imprimir contenido del arreglo
            for (j = 0; j < k; j++) {
                mensaje += ((j + 1) + "-: " + burbuja.get(j) + "\n");
            }

            JOptionPane.showMessageDialog(null, mensaje);
            mensaje = "";
        }//GEN-LAST:event_jButtonContenidoActionPerformed


    }//GEN-LAST:event_jButtonContenidoActionPerformed

    private void jButtonOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarActionPerformed
        {//GEN-FIRST:event_jButtonOrdenarActionPerformed
            try {
                //metodo de la burbuja              
                for (x = 0; x < k; x++) {//la veces que encuentra un espacio es k
                    for (y = 0; y < k; y++) {//le pongo un limite de k veces porque es el numero de datos que entro
                        int uno = Integer.parseInt(burbuja.get(x).toString());//convierto los String a enteros para poder compararlos con el if
                        int dos = Integer.parseInt(burbuja.get(y).toString());

                        if (uno <= dos) {
                            //aux = burbuja[x];
                            aux = Integer.parseInt(burbuja.get(x).toString());
                            //burbuja[x]=burbuja[y];                                                  
                            burbuja.set(x, burbuja.get(y));
                            //burbuja[y]=aux;
                            burbuja.set(y, aux);
                        }
                    }
                }
                JOptionPane.showMessageDialog(null, "¡Listo!, los números se han ordenado");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al introducir datos, porfavor verifica los números o espacios");
            }
        }//GEN-LAST:event_jButtonOrdenarActionPerformed
    }//GEN-LAST:event_jButtonOrdenarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        {//GEN-FIRST:event_jButtonSalirActionPerformed
            System.exit(0);
        }//GEN-LAST:event_jButtonSalirActionPerformed
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        {//GEN-FIRST:event_jButtonNuevoActionPerformed
            LimpiarTxt();
            for (i = 0; i < burbuja.size(); i++) {
                burbuja.set(i, (""));
                burbuja.remove(i--);
            }

            i = 0;
            j = 0;
            k = 0;
            x = 0;
            y = 0;
            aux = 0;
            inicio = 0;
            contador = 0;
            mensaje = "";
            entrada1 = "";
            temporal = "";
            datos = "";

            jTextField1Entrada.requestFocus();
        }//GEN-LAST:event_jButtonNuevoActionPerformed
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Burbuja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Burbuja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Burbuja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Burbuja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Burbuja().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonContenido;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JButton jButtonOrdenar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1Entrada;
    // End of variables declaration//GEN-END:variables
}
